"""Parse rendered HTML from the C2PA public spec site.

Extracts validation rules and status codes from the Antora-rendered HTML at
spec.c2pa.org. This parser replaces the AsciiDoc parser for pipelines that
use the public site instead of the private specs-core repository.

Entry points:
- parse_html_status_codes: StatusCode objects from the 3 standard tables.
- parse_html_validation_rules: ValidationRule objects from Section 15.
- parse_html_spec: Convenience wrapper returning both.

The HTML is generated by Antora 3.x from AsciiDoc source. Its structure is
stable and predictable:
- Status code tables have IDs: validation_success_codes,
  validation_informational_codes, validation_failure_codes.
- Section 15 starts at id="validation-clause".
- Normative text appears in <p> and <li> elements.
- Admonition blocks use class="admonitionblock" and are non-normative.
"""

from __future__ import annotations

import html as html_module
import re
from pathlib import Path

from c2pa_kg.models import StatusCode, ValidationRule
from c2pa_kg.parsers._normative import (
    CAMEL_RE,
    detect_severity,
    has_normative_keyword,
    infer_phase,
    split_sentences,
)

# ---------------------------------------------------------------------------
# Tag / entity helpers
# ---------------------------------------------------------------------------

_TAG_RE = re.compile(r"<[^>]+>")

# Extract identifier-like tokens from <code> tags (HTML equivalent of AsciiDoc
# backtick-quoted identifiers).
_CODE_IDENT_RE = re.compile(r"<code>([A-Za-z][A-Za-z0-9._\-]*)</code>")

# ---------------------------------------------------------------------------
# Concept vocabulary: maps natural language C2PA terms to KG entity identifiers.
# Multi-word phrases are checked first (longest match wins). Single-word
# fallbacks catch rules that use common spec nouns without formal identifiers.
# ---------------------------------------------------------------------------

_CONCEPT_PHRASES: list[tuple[str, list[str]]] = [
    # Multi-word phrases (order: longest/most-specific first)
    ("c2pa manifest store", ["manifest"]),
    ("manifest store", ["manifest"]),
    ("c2pa manifest", ["manifest"]),
    ("active manifest", ["manifest"]),
    ("manifest consumer", ["manifest"]),
    ("claim generator", ["claim"]),
    ("claim signature", ["signature"]),
    ("trust anchor", ["PublicCredential"]),
    ("trust list", ["PublicCredential"]),
    ("chain of trust", ["PublicCredential"]),
    ("hard binding", ["DataHashMap"]),
    ("soft binding", ["SoftBindingMap"]),
    ("merkle tree", ["MerkleMap"]),
    ("hashed uri", ["HashedUriMap"]),
    ("hashed-uri", ["HashedUriMap"]),
    ("time-stamp", ["TimeStampMap"]),
    ("multi-asset hash", ["MultiAssetHashMap"]),
    ("ingredient assertion", ["IngredientMap"]),
    ("ingredient manifest", ["IngredientMap"]),
    ("validation result", ["validationResults"]),
    ("status code", ["StatusCodesMap"]),
    ("external data", ["HashedExtUriMap"]),
    ("external reference", ["HashedExtUriMap"]),
    ("cloud data", ["CloudDataMap"]),
    ("digital signature", ["signature"]),
    ("x.509", ["certificateInfo"]),
]

# Single-word patterns matched with word boundaries. These are only applied
# when no <code>-tag entities and no phrase matches were found, to avoid
# polluting rules that already have precise entity links.
_CONCEPT_WORDS: list[tuple[re.Pattern[str], list[str]]] = [
    (re.compile(r"\bmanifests?\b", re.IGNORECASE), ["manifest"]),
    (re.compile(r"\bclaims?\b", re.IGNORECASE), ["claim"]),
    (re.compile(r"\bassertions?\b", re.IGNORECASE), ["assertions"]),
    (re.compile(r"\bvalidators?\b", re.IGNORECASE), ["manifest"]),
    (re.compile(r"\bgenerators?\b", re.IGNORECASE), ["claim"]),
    (re.compile(r"\bingredients?\b", re.IGNORECASE), ["IngredientMap"]),
    (re.compile(r"\bcertificates?\b", re.IGNORECASE), ["certificateInfo"]),
    (re.compile(r"\bcredentials?\b", re.IGNORECASE), ["PublicCredential"]),
    (re.compile(r"\btimestamps?\b", re.IGNORECASE), ["TimeStampMap"]),
    (re.compile(r"\bOCSP\b"), ["CertificateStatusMap"]),
    (re.compile(r"\bfonts?\b", re.IGNORECASE), ["FontInfoMap"]),
    (re.compile(r"\bhashing\b", re.IGNORECASE), ["DataHashMap"]),
    (re.compile(r"\bblocks?\b", re.IGNORECASE), ["BmffHashMap"]),
    (re.compile(r"\bassets?\b", re.IGNORECASE), ["manifest"]),
]

# Section header keywords that imply entity context when the rule text itself
# contains no identifiable concept. Maps section title substrings to entities.
_SECTION_ENTITY_MAP: list[tuple[str, list[str]]] = [
    ("manifest store", ["manifest"]),
    ("signature", ["signature"]),
    ("trust", ["PublicCredential"]),
    ("credential", ["PublicCredential"]),
    ("certificate", ["certificateInfo"]),
    ("ocsp", ["CertificateStatusMap"]),
    ("ingredient", ["IngredientMap"]),
    ("assertion", ["assertions"]),
    ("hash", ["DataHashMap"]),
    ("binding", ["DataHashMap"]),
    ("time-stamp", ["TimeStampMap"]),
    ("timestamp", ["TimeStampMap"]),
    ("merkle", ["MerkleMap"]),
    ("font", ["FontInfoMap"]),
    ("content", ["DataHashMap"]),
    ("revocation", ["CertificateStatusMap"]),
]


def _strip_tags(text: str) -> str:
    """Remove HTML tags, decode entities, and normalize whitespace."""
    text = _TAG_RE.sub("", text)
    text = html_module.unescape(text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def _concept_entities(text: str, section: str = "") -> list[str]:
    """Extract entity refs from natural language C2PA concepts in text.

    Applies multi-word phrase matching, then single-word fallback, then
    section-header inference. Returns deduplicated entity identifiers.
    """
    text_lower = text.lower()
    refs: list[str] = []

    # Phase 1: multi-word phrases
    for phrase, entities in _CONCEPT_PHRASES:
        if phrase in text_lower:
            refs.extend(entities)

    # Phase 2: single-word fallback (only if phrases found nothing)
    if not refs:
        for pattern, entities in _CONCEPT_WORDS:
            if pattern.search(text):
                refs.extend(entities)
                break  # take first match to avoid noise

    # Phase 3: section-header inference (last resort)
    if not refs and section:
        section_lower = section.lower()
        for keyword, entities in _SECTION_ENTITY_MAP:
            if keyword in section_lower:
                refs.extend(entities)
                break

    return list(dict.fromkeys(refs))


def _extract_html_entities(raw_html: str, section: str = "") -> list[str]:
    """Extract entity references from raw HTML.

    Combines three strategies:
    1. Identifier tokens inside <code> tags (field names, status codes).
    2. CamelCase words in plain text.
    3. Concept vocabulary matching on natural language noun phrases.

    The concept vocabulary is applied only when strategies 1+2 yield nothing,
    preventing noise on rules that already have precise structural refs.
    """
    refs: list[str] = []
    for m in _CODE_IDENT_RE.finditer(raw_html):
        token = m.group(1)
        if "." in token or "_" in token or token[0].islower():
            refs.append(token)
    plain = _strip_tags(raw_html)
    for m in CAMEL_RE.finditer(plain):
        refs.append(m.group(1))

    # If structural extraction found nothing, fall back to concept vocabulary.
    if not refs:
        refs = _concept_entities(plain, section)

    return list(dict.fromkeys(refs))  # deduplicate preserving order


# ---------------------------------------------------------------------------
# Status code extraction
# ---------------------------------------------------------------------------

_TABLE_ID_TO_CATEGORY: dict[str, str] = {
    "validation_success_codes": "success",
    "validation_informational_codes": "informational",
    "validation_failure_codes": "failure",
}

# Match a table by its ID and capture everything up to </table>.
_TABLE_BY_ID_RE = re.compile(
    r'<table\s+id="(validation_(?:success|informational|failure)_codes)"[^>]*>'
    r"(.*?)</table>",
    re.DOTALL,
)

# Match a <tbody>...</tbody> block.
_TBODY_RE = re.compile(r"<tbody>(.*?)</tbody>", re.DOTALL)

# Match a single table row with 3 cells.
_ROW_RE = re.compile(
    r"<tr>\s*"
    r"<td[^>]*>(.*?)</td>\s*"
    r"<td[^>]*>(.*?)</td>\s*"
    r"<td[^>]*>(.*?)</td>\s*"
    r"</tr>",
    re.DOTALL,
)

# Extract the first <code> value from a cell.
_FIRST_CODE_RE = re.compile(r"<code>([^<]+)</code>")


def parse_html_status_codes(html_text: str) -> list[StatusCode]:
    """Extract all status codes from the 3 standard validation tables.

    Returns a list of StatusCode objects with code, meaning, url_usage, and
    category populated.
    """
    codes: list[StatusCode] = []

    for table_match in _TABLE_BY_ID_RE.finditer(html_text):
        table_id = table_match.group(1)
        table_body = table_match.group(2)
        category = _TABLE_ID_TO_CATEGORY[table_id]

        tbody_match = _TBODY_RE.search(table_body)
        if not tbody_match:
            continue

        for row_match in _ROW_RE.finditer(tbody_match.group(1)):
            cell1 = row_match.group(1)
            cell2 = row_match.group(2)
            cell3 = row_match.group(3)

            # The status code is inside the first <code> tag of cell 1.
            code_match = _FIRST_CODE_RE.search(cell1)
            if not code_match:
                continue

            code_val = code_match.group(1).strip()

            # Skip header rows that slipped through.
            if code_val.lower() in ("value", "code"):
                continue

            meaning = _strip_tags(cell2)
            url_usage = _strip_tags(cell3)

            codes.append(
                StatusCode(
                    code=code_val,
                    meaning=meaning,
                    url_usage=url_usage,
                    category=category,
                )
            )

    return codes


# ---------------------------------------------------------------------------
# Validation rule extraction
# ---------------------------------------------------------------------------

# Locate Section 15 boundaries.
_VALIDATION_SECTION_START_RE = re.compile(
    r'<h2\s+id="validation-clause"[^>]*>',
)
_NEXT_H2_RE = re.compile(r"<h2\s+")

# Section headers within validation section (h3-h6).
_SECTION_HEADER_RE = re.compile(
    r"<h([3-6])\s+id=\"([^\"]*)\"\s*>"
    r"(?:<a[^>]*></a>)?"
    r"\s*([\d.]+\s+.+?)</h\1>",
    re.DOTALL,
)

# Blocks to remove before extracting normative text.
# Admonition blocks: <div class="admonitionblock ...">...(table)...</div>
_ADMONITION_RE = re.compile(
    r'<div class="admonitionblock[^"]*">.*?</table>\s*</div>',
    re.DOTALL,
)
# Listing/code blocks: <div class="listingblock">...</div></div>
_LISTINGBLOCK_RE = re.compile(
    r'<div class="listingblock">.*?</pre>\s*</div>\s*</div>',
    re.DOTALL,
)
# Image blocks.
_IMAGEBLOCK_RE = re.compile(
    r'<div[^>]*class="imageblock[^"]*"[^>]*>.*?</div>\s*</div>',
    re.DOTALL,
)
# Status code tables (already handled separately).
_STATUS_TABLE_RE = re.compile(
    r'<table\s+id="validation_(?:success|informational|failure)_codes"[^>]*>'
    r".*?</table>",
    re.DOTALL,
)
# Any remaining <table> elements (CDDL inline tables, etc.).
_ANY_TABLE_RE = re.compile(r"<table[^>]*>.*?</table>", re.DOTALL)

# Text extraction patterns.
_PARAGRAPH_TEXT_RE = re.compile(
    r'<div class="paragraph">\s*<p>(.*?)</p>\s*</div>',
    re.DOTALL,
)
_LIST_ITEM_RE = re.compile(
    r"<li>\s*<p>(.*?)</p>",
    re.DOTALL,
)


def _extract_validation_section(html_text: str) -> str:
    """Return the raw HTML for Section 15 (Validation)."""
    start_match = _VALIDATION_SECTION_START_RE.search(html_text)
    if not start_match:
        return ""

    start_pos = start_match.start()
    # Find the next <h2 after the validation section start.
    remaining = html_text[start_match.end() :]
    end_match = _NEXT_H2_RE.search(remaining)
    if end_match:
        end_pos = start_match.end() + end_match.start()
    else:
        end_pos = len(html_text)

    return html_text[start_pos:end_pos]


def _clean_section(section_html: str) -> str:
    """Remove non-normative blocks from the validation section HTML."""
    text = section_html
    text = _ADMONITION_RE.sub("", text)
    text = _LISTINGBLOCK_RE.sub("", text)
    text = _IMAGEBLOCK_RE.sub("", text)
    text = _STATUS_TABLE_RE.sub("", text)
    text = _ANY_TABLE_RE.sub("", text)
    return text


def _extract_section_headers(section_html: str) -> list[tuple[int, str]]:
    """Return (offset, title) pairs for h3-h6 headers in the section."""
    headers: list[tuple[int, str]] = []
    for m in _SECTION_HEADER_RE.finditer(section_html):
        title = _strip_tags(m.group(3))
        headers.append((m.start(), title))
    return headers


def _section_at(offset: int, headers: list[tuple[int, str]]) -> str:
    """Return the nearest preceding section header title."""
    title = ""
    for start, h_title in headers:
        if start <= offset:
            title = h_title
        else:
            break
    return title


def parse_html_validation_rules(html_text: str) -> list[ValidationRule]:
    """Extract ValidationRule objects from Section 15 of the rendered HTML.

    Skips admonition blocks, code listings, tables, and images. Processes
    paragraphs and list items for RFC 2119 normative keywords.
    """
    section_html = _extract_validation_section(html_text)
    if not section_html:
        return []

    headers = _extract_section_headers(section_html)
    cleaned = _clean_section(section_html)

    rules: list[ValidationRule] = []
    rule_counter: dict[str, int] = {}

    # Collect all text blocks: paragraphs and list items.
    text_blocks: list[tuple[int, str]] = []

    for m in _PARAGRAPH_TEXT_RE.finditer(cleaned):
        # Use the match position in the cleaned text for section lookup.
        text_blocks.append((m.start(), m.group(1)))

    for m in _LIST_ITEM_RE.finditer(cleaned):
        text_blocks.append((m.start(), m.group(1)))

    # Sort by position so section headers track correctly.
    text_blocks.sort(key=lambda x: x[0])

    for offset, raw_html in text_blocks:
        plain = _strip_tags(raw_html)
        if not plain or len(plain) < 20:
            continue
        if not has_normative_keyword(plain):
            continue

        section = _section_at(offset, headers)
        phase = infer_phase(section, plain)
        phase_key = phase.value

        # Extract entity references from raw HTML (before tag stripping)
        # so <code> tags are available for identifier detection.
        block_entities = _extract_html_entities(raw_html, section)

        for sentence in split_sentences(plain):
            if not has_normative_keyword(sentence):
                continue

            severity = detect_severity(sentence)
            if len(sentence) < 20:
                continue

            rule_counter[phase_key] = rule_counter.get(phase_key, 0) + 1
            rule_id = f"VAL-{phase_key.upper()[:4]}-{rule_counter[phase_key]:04d}"

            # Use block-level entities since sentence-level extraction
            # operates on stripped text where <code> tags are gone.
            entities = block_entities

            rules.append(
                ValidationRule(
                    rule_id=rule_id,
                    description=sentence[:500],
                    severity=severity,
                    phase=phase,
                    condition="",
                    action="",
                    referenced_entities=entities[:10],
                    spec_section=section,
                    source_text=sentence[:200],
                )
            )

    return rules


# ---------------------------------------------------------------------------
# Public convenience API
# ---------------------------------------------------------------------------


def parse_html_spec(
    html_text: str,
) -> tuple[list[ValidationRule], list[StatusCode]]:
    """Parse a rendered C2PA spec HTML page.

    Extracts both validation rules (from Section 15 prose) and status codes
    (from the 3 standard tables).

    Args:
        html_text: Full HTML content of the C2PA specification page.

    Returns:
        Tuple of (list[ValidationRule], list[StatusCode]).
    """
    rules = parse_html_validation_rules(html_text)
    codes = parse_html_status_codes(html_text)
    return rules, codes


def parse_html_spec_file(
    html_path: Path,
) -> tuple[list[ValidationRule], list[StatusCode]]:
    """Parse a locally saved C2PA spec HTML file.

    Convenience wrapper that reads the file and calls parse_html_spec.
    """
    text = html_path.read_text(encoding="utf-8")
    return parse_html_spec(text)
